model_type: classification # regression | classification | timeseries

train_start_date: "2025-01-01"
train_end_date: "2025-12-31"
val_start_date: "2026-01-01"
val_end_date: "2026-05-31"

data:
  enabled: true
  symbol: BTC
  exchange: binance
  timeframe: 15m
  start_date: "2025-01-01"
  end_date: "2026-06-01"

features:
  enabled: true

  indicators:
    EMA:
      - parameters:
          timeperiod: 20
        aliases:
          ema: ind_EMA_20

      - parameters:
          timeperiod: 50
        aliases:
          ema: ind_EMA_50

    RSI:
      - parameters:
          timeperiod: 14
        aliases:
          rsi: ind_RSI_14

    MACD:
      - parameters:
          fastperiod: 12
          slowperiod: 26
          signalperiod: 9
        aliases:
          macd: ind_MACD_12_26_9
          macd_signal: ind_MACD_SIGNAL_12_26_9
          macd_hist: ind_MACD_HIST_12_26_9

    PATTERNS:
      DOJI:
        aliases:
          pattern: pat_DOJI

      ENGULFING:
        aliases:
          pattern: pat_BULLISH_ENGULFING

  sentiment:
    enabled: true
    source:
      - reddit
    aliases:
      sentiment: sen_MARKET

target:
  classification:
    - source: close
      method: future_direction
      horizon: 5
      threshold: 0.30
      classes:
        positive: 1
        negative: -1
        neutral: 0

  regression:
    - source: close
      method: future_return
      horizon: 5
  
  timeseries:
    - source: close
      method: next_close
      horizon: 1

primary_metric: avg_return

models:
  classification:
    - name: logistic_regression
    - name: decision_tree
    - name: random_forest
    - name: extra_trees
    - name: xgboost
    - name: lightgbm
    - name: catboost
    - name: svm

    - name: bilstm
      params:
        sequence_length: 60
        hidden_units: [64, 32]
        dropout: 0.3
        recurrent_dropout: 0.2
        dense_units: 16
        activation: relu
        output_activation: softmax
        optimizer: adam
        learning_rate: 0.001
        loss: categorical_crossentropy
        metrics: ['accuracy']
        batch_size: 32
        epochs: 10
        early_stopping_patience: 3

  regression:
    - name: lightgbm
    - name: svr
    - name: linear_regression
    - name: catboost
    - name: xgboost
    - name: ridge
    - name: lasso
    - name: random_forest
    - name: extra_trees

    - name: gru
      params:
        sequence_length: 60
        hidden_units: [64, 32]
        dropout: 0.2
        recurrent_dropout: 0.2
        dense_units: 16
        activation: relu
        output_activation: linear
        optimizer: adam
        learning_rate: 0.001
        batch_size: 32
        epochs: 10
        loss: mse
        metrics:
          - mae
        early_stopping_patience: 3